const OPEN_RECIPE_CREATE = 'OPEN_RECIPE_CREATE';
const OPEN_RECIPES = 'OPEN_RECIPES';
const SAVE_RECIPE = 'SAVE_RECIPE';
const SET_RECIPES = 'SET_RECIPES';

export default {
    OPEN_RECIPE_CREATE,
    OPEN_RECIPES,
    SAVE_RECIPE,
    SET_RECIPES,
};
