const OPEN_RECIPE_CREATE = 'OPEN_RECIPE_CREATE';

const OPEN_RECIPES = 'OPEN_RECIPES';
const SET_RECIPES = 'SET_RECIPES';
const GET_RECIPES = 'GET_RECIPES';

const SAVE_RECIPE = 'SAVE_RECIPE';
const OPEN_RECIPE = 'OPEN_RECIPE';
const SET_RECIPE = 'SET_RECIPE';
const GET_RECIPE = 'GET_RECIPE';
const DELETE_RECIPE = 'DELETE_RECIPE';

export default {
    OPEN_RECIPE_CREATE,

    OPEN_RECIPES,
    SET_RECIPES,
    GET_RECIPES,

    SAVE_RECIPE,
    OPEN_RECIPE,
    SET_RECIPE,
    GET_RECIPE,
    DELETE_RECIPE,
};
